### PR TITLE
Updated the script with ffuf

### PR DESCRIPTION
**Pull request by theinit01**
**Pull Request Title:**

Updated Script, README, and setup.sh for Replacing Gobuster with ffuf

**Pull Request Description:**

Hi there,

I've made a significant update to the Bug Bounty reconnaissance script along with changes to the README and setup script to replace Gobuster with ffuf. This change enhances the tool's functionality and performance.

**Summary of Changes:**

1. **Script Update:** I've modified the main script to replace Gobuster with ffuf for enhanced directory and file brute-forcing.
2. **README Update:** The README has been updated to reflect the change.
3. **setup.sh Enhancement:** The setup script has been updated to include ffuf installation and configuration.

I look forward to your feedback and suggestions.

Issue mentioned: #38

### CODE REVIEW

**Comment by theinit01** [comment]
@chvancooten, I have updated the script. Review it whenever you are free.

**Comment by theinit01** [comment]
@chvancooten, what can be done to pass the build test?

**Comment by chvancooten** [comment]
Looks like it failed due to an issue with the secret not being set outside of the main branch (which is my bad). One thing to note though is that the runTests file would also need to be edited for the new tool, otherwise the build will fail later down in the chain I think

**Comment by theinit01** [comment]
I am looking into it.

**Comment by theinit01** [comment]
I've updated the runTests.sh file.

**Comment by chvancooten** [comment]
Thanks, looking at the code it looks good to me for now. I will test more, fix the pipeline, and merge when I get back in December! Thanks for the work! 🙏

**Comment by theinit01** [comment]
@chvancooten, actually I was trying to participate in the hacktoberfest. It would be great if you could review earlier. Its totally fine too if you are not available right now.

**Comment by chvancooten** [comment]
I see! No worries, you definitely deserve a point for that 😁. I have added the 'HACKTOBERFEST-ACCEPTED' label which should automatically make this PR considered as a valid entry, without merging it for now. Please double check if it counts towards your points total and otherwise let me know!

**Comment by theinit01** [comment]
@chvancooten, Thank you!!! They have considered it as a valid entry.

**Comment by chvancooten** [comment]
Closing this one as the changes have been merged into dev as part of #50

**Pull request closed without merging**
