### PR TITLE
Added Contributers' avatars in the README file

### PR DESCRIPTION
**Pull request by theinit01**
image

### CODE REVIEW

**Comment by theinit01** [comment]
@chvancooten, review the changes as your schedule allows.

**Comment by chvancooten** [comment]
I like it! It seems like the other PR changes are also included in this PR change history though?

**Comment by theinit01** [comment]
@chvancooten, I created separate branches for each pr.

**Comment by theinit01** [comment]
I found the issue and am now working on it.

**Comment by theinit01** [comment]
@chvancooten, I have created another PR with the required changes. You can review it now.

**Comment by theinit01** [comment]
let this one be as it is and review the PR #54

**Pull request closed without merging**
