### PR TITLE
Allow configurable output directory #12

### PR DESCRIPTION
**Pull request by denvera**

### CODE REVIEW

**Comment by chvancooten** [comment]
Looks good, thanks! Any particular reason you chose not to create the chosen output dir if it does not exist?

**Comment by denvera** [comment]
No particular reason, would you prefer that? Happy to quickly make the
change!

Kind regards,
Denver Abrey
denvera@gmail.com
083 281 3432

**Comment by chvancooten** [comment]
I think the ideal setup would be that it prompts the user to create to create the directory or not. If not -> exit (as it is now).
Thanks, that would be great!

**Comment by chvancooten** [comment]
Thanks a lot @denvera!

**Pull request merged**
